CMS/urls.py
from django.conf.urls import url
from django.contrib import admin
from fault_reporting import views
from django.views.static import serve  # 用户上传文件用的模块
from django.conf import settings  # 同样是上传用的
from django.conf.urls import url, include
from fault_reporting import urls as fault_report_urls  # 二级路由

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', views.LoginView.as_view()),
    url(r'^index/$', views.index),
    url(r'^logout/$', views.logout),
    url(r'^vcode/$', views.vcode),
    url(r'^change_password/$', views.change_password),
    # 注册
    url(r'^register/$', views.RegisterView.as_view()),
    # 编辑注册信息
    url(r'^edit_info/$', views.edit_register),
    # 给用户上传的那些文件路径做认证上传头像的
    url(r'^media/(?P<path>.*)', serve, {"document_root": settings.MEDIA_ROOT}),
    # 故障总结主页面
    url(r'^fault-report/', include(fault_report_urls)),  # 以fault-report开头的所有路由都交给二级路由去处理









]

fault_reporting/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class UserInfo(AbstractUser):
    phone=models.CharField(max_length=11)
    avatar=models.FileField(upload_to="avatars/",default="avatars/default.png")


class LOB(models.Model):
    """
    业务线
    """
    title = models.CharField(max_length=32, unique=True, verbose_name="业务线名称")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "业务线"
        verbose_name_plural = verbose_name


class Tag(models.Model):
    """
    故障标签
    """
    title = models.CharField(max_length=32, verbose_name="标签名称", unique=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "标签"
        verbose_name_plural = verbose_name


class UpDown(models.Model):
    """django_admin_log
    支持或反对
    同一个用户只能对一篇故障总结点支持或反对
    支持或反对只能二选一：点了支持就不能点反对，反之亦然
    """
    user = models.ForeignKey(to="UserInfo", verbose_name="用户")
    fault_report = models.ForeignKey(to="FaultReport", verbose_name="故障总结")
    is_up = models.BooleanField(default=True, verbose_name="支持/反对")

    def __str__(self):
        return "{}-{}-{}".format(self.user.username, self.fault_report, "支持" if self.is_up else '反对')

    class Meta:
        # 联合唯一
        # 限制一个用户只能给一篇故障总结点赞或反对一次
        unique_together = (("fault_report", "user"),)
        verbose_name = "支持/反对"
        verbose_name_plural = verbose_name


class Comment(models.Model):
    """
    评论
    """
    fault_report = models.ForeignKey(to="FaultReport", verbose_name="故障总结")
    user = models.ForeignKey(to="UserInfo")
    content = models.CharField(max_length=255)  # 评论内容
    create_time = models.DateTimeField(auto_now_add=True)
    # 自己关联自己的情况
    parent_comment = models.ForeignKey(to="self", null=True, blank=True)

    def __str__(self):
        return self.content

    class Meta:
        verbose_name = "评论"
        verbose_name_plural = verbose_name


class FaultReport(models.Model):
    """
    故障总结/故障报告
    """
    title = models.CharField(max_length=80, verbose_name="故障标题")
    desc = models.CharField(max_length=255, verbose_name="故障简介")
    create_time = models.DateTimeField(auto_now_add=True, verbose_name="发布时间")
    modify_time = models.DateTimeField(auto_now=True, verbose_name="最后修改时间")

    comment_count = models.IntegerField(default=0)
    up_count = models.IntegerField(default=0)
    down_count = models.IntegerField(default=0)

    lob = models.ForeignKey(to="LOB", null=True, verbose_name="所属业务线")

    user = models.ForeignKey(to="UserInfo", verbose_name="发布者")

    tags = models.ManyToManyField(
        to="Tag",
        through="Fault2Tag",  # 指定第三张关系表
        through_fields=("fault_report", "tag"),  # 通过哪些字段建立多对多关系
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "故障总结/故障报告"
        verbose_name_plural = verbose_name


class Fault2Tag(models.Model):
    """
    故障报告和标签的多对多关系表
    """
    fault_report = models.ForeignKey(to="FaultReport", on_delete=models.CASCADE)
    tag = models.ForeignKey(to="Tag")

    def __str__(self):
        return "{}-{}".format(self.fault_report, self.tag)

    class Meta:
        unique_together = (("fault_report", "tag"),)
        verbose_name = "故障-标签"
        verbose_name_plural = verbose_name


class FaultDetail(models.Model):
    """
    故障详情表
    """
    content = models.TextField()
    fault = models.OneToOneField(to="FaultReport")

    def __str__(self):
        return self.content[0:50]

    class Meta:
        verbose_name = "故障详情表"
        verbose_name_plural = verbose_name

templates/add_report.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加新的故障总结</title>
    <link rel="stylesheet" href="/static/plugins/bootstrap-3.3.7/css/bootstrap.min.css">
</head>
<body>
{% include "base.html" %}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <form action="" method="post">
            {% csrf_token %}
                <div class="form-group">
                    <label for="title">标题</label>
                    <input type="text" id="title" name="title" class="form-control">
                </div>
                <div class="form-group">
                    <label for="content">内容</label>
                    <textarea class="form-control" name="content" id="content" rows="20"></textarea>
                </div>
                <div class="form-group">
                    <label for="">所属业务线</label>
                    <select name="lob" id="lob">
                        {% for lob in lobs %}
                        <option value="{{ lob.id }}">{{ lob.title }}</option>
                        {% endfor %}
                    </select>
                </div>
                <button class="btn btn-success" type="submit">发布</button>
            </form>
        </div>
    </div>
</div>
<script src="/static/plugins/jquery-3.3.1.min.js"></script>
<script charset="utf-8" src="/static/plugins/kindeditor/kindeditor-all-min.js"></script>
<script charset="utf-8" src="/static/plugins/kindeditor/lang/zh-CN.js"></script>

<script>
        KindEditor.ready(function(K) {
                window.editor = K.create('#content', {
                    uploadJson: "/fault-report/upload-img/",
                    extraFileUploadParams : {  // 上传文件时额外传递的参数
                        csrfmiddlewaretoken : $("[name='csrfmiddlewaretoken']").val(),
                }
                });
        });
</script>
</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
    <link rel="stylesheet" href="/static/plugins/bootstrap-3.3.7/css/bootstrap.min.css">
{#    <link rel="stylesheet" href="/static/css/my-style.css">#}
</head>
<body>

<!-- 导航条 -->
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">CMS</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="active"><a href="#">报障系统</a></li>
                <li><a href="/index/">首页</a></li>
                <li><a href="/fault-report/add-report/">发布</a></li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                {% if request.user.username %}
                    <li><img style="height: 50px;width: 50px;border-radius: 50%" src="/media/{{ request.user.avatar }}">
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">{{ request.user.username }}<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="/fault-report/info/">个人中心</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="/logout/">注销</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li><a href="/login/">登录</a></li>
                    <li><a href="/register/">注册</a></li>
                {% endif %}

            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>


<!--页面主要内容-->
<div class="container-fluid">
    <div class="row">
        <div class="col-md-2">
           {% block page-left %}

            {% endblock %}

        </div>
        <div class="col-md-10">

            {% block page-right %}

            {% endblock %}

        </div>
    </div>
</div>


<script src="/static/plugins/jquery-3.3.1.min.js"></script>
<script src="/static/plugins/bootstrap-3.3.7/js/bootstrap.min.js"></script>
</body>
</html>

templates/change_password.html
{% extends 'base.html' %}

{% block page-js %}

    <script src="/static/js/change.js"></script>
{% endblock %}

{% block page-left %}
    <div class="panel panel-info">
        <div class="panel-heading">
            <h3 class="panel-title">内容管理</h3>
        </div>
        <div class="panel-body">
            <a class="btn btn-default btn-block" href="/fault-report/add-report/">发布</a>
            <hr>
            <p><a href="">我的评论</a></p>
        </div>
    </div>
    <div class="panel panel-info">
        <div class="panel-heading">
            <h3 class="panel-title">资料管理</h3>
        </div>
        <div class="panel-body">
            <p><a href="/change_password/">修改密码</a></p>
            <p><a href="/edit_info/">修改信息</a></p>
        </div>
    </div>
{% endblock %}

{% block page-right %}
    <div class="col-md-12">
        <div class="panel panel-success">
            <div class="panel-heading">
                <h3 class="panel-title">更改密码</h3>
            </div>
            <div class="panel-body login-box">
                <form action="" method="post">
                     {% csrf_token %}
                    <div class="form-group" style="margin-top: 20px">
                        <label for="inputEmail3" class="col-md-2 control-label">旧密码</label>
                        <div class="col-md-10">
                            <input type="password" class="form-control" id="inputEmail3" name="old_password"
                                   placeholder="旧密码">
                            <p class="error_old">{{ error_old }}</p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputPassword3" class="col-sm-2 control-label">新密码</label>
                        <div class="col-sm-10">
                            <input style="" type="password" class="form-control" id="inputPassword3" name="new_password"
                                   placeholder="新密码">
                            <p></p>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="inputPassword3" class="col-sm-2 control-label">再次输入新密码</label>
                        <div class="col-sm-10">
                            <input type="password" class="form-control" id="inputPassword3" placeholder="再次输入新密码"
                                   name="repeat_password">
                            <p class="error_new">{{ error_new }}</p>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-offset-6 col-sm-10" style="margin: 0 auto;">
                            <button type="submit" class="btn btn-success">提交</button>
                            <a href="/index/" class="btn btn-warning">取消</a>

                        </div>
                    </div>


                </form>

            </div>
        </div>
    </div>



{% endblock %}

templates/edit_register.html
{#<!--注释#}
{# form_obj就是<label for="id_username">用户名:</label></th><td><input type="text" name="username" minlength="2"#}
{#class="form-control" required id="id_username" />#}
{#{{ field.id_for_label }} 就是id#}
{#{{ field.label }}就是字段名#}
{#{{ field }}就是input标签#}



{% extends 'base.html' %}
{% block page-css %}
    <link rel="stylesheet" href="/static/plugins/bootstrap-3.3.7/css/bootstrap.min.css">
    {#    <link rel="stylesheet" href="/static/css/mycss.css">#}

{% endblock %}


{% block page-js %}
{#    <script src="/static/plugins/jquery-3.3.1.min.js"></script>#}
{#    <script src="/static/plugins/bootstrap-3.3.7/js/bootstrap.min.js"></script>#}
    <script src="/static/js/edit_register.js"></script>
{% endblock %}
{% block page-left %}
    <div class="panel panel-info">
        <div class="panel-heading">
            <h3 class="panel-title">内容管理</h3>
        </div>
        <div class="panel-body">
            <a class="btn btn-default btn-block" href="/fault-report/add-report/">发布</a>
            <hr>
            <p><a href="">我的评论</a></p>
        </div>
    </div>
    <div class="panel panel-info">
        <div class="panel-heading">
            <h3 class="panel-title">资料管理</h3>
        </div>
        <div class="panel-body">
            <p><a href="/change_password/">修改密码</a></p>
            <p><a href="/edit_info/">修改信息</a></p>
        </div>
    </div>
{% endblock %}

{% block page-right %}
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <form  action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="title">用户名</label>
                        <input type="text" id="title" name="name" class="form-control" value="{{ user_obj.username }}">
                    </div>
                    <div class="form-group">
                        <label for="title">电话</label>
                        <input type="text" id="title" name="phone" class="form-control" value="{{ user_obj.phone }}">
                    </div>
                    <div class="form-group">
                        <label for="title">邮箱</label>
                        <input type="text" id="title" name="email" class="form-control" value="{{ user_obj.email }}">
                    </div>

                    <div class="form-group">
                        <label for="id_avatar">头像
                            <img name="avatar" src="/media/{{ user_obj.avatar }}" id="avatar-img" style="width: 60px">
                        </label>
                        <input name="avatar" type="file" id="id_avatar" accept="image/*" class="form-control" style="display: none">

                    </div>
                    <div style="text-align: center">
                        <button style="width: 100px" type="submit" class="btn btn-success" id="submit-btn">提交</button>
                    </div>

                </form>
            </div>
        </div>

    </div>
{% endblock %}

templates/edit_report.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加新的故障总结</title>
    <link rel="stylesheet" href="/static/plugins/bootstrap-3.3.7/css/bootstrap.min.css">
</head>
<body>
{% include "base.html" %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <form action="" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="title">标题</label>
                    <input type="text" id="title" name="title" class="form-control" value="{{ report_obj.title }}">
                </div>
                <div class="form-group">
                    <label for="content">内容</label>
                    <textarea class="form-control" name="content" id="content" rows="20">
                        {{ report_obj.faultdetail.content }}
                    </textarea>
                </div>
                <div class="form-group">
                    <label for="">所属业务线</label>
                    <select name="lob" id="lob">
                        {% for lob in lobs %}
                            {% if lob == report_obj.lob %}
                                <option selected value="{{ lob.id }}">{{ lob.title }}</option>
                            {% else %}
                                <option value="{{ lob.id }}">{{ lob.title }}</option>
                            {% endif %}
                        {% endfor %}
                    </select>
                </div>
                <button class="btn btn-success" type="submit">发布</button>
            </form>
        </div>
    </div>
</div>
<script src="/static/plugins/jquery-3.3.1.min.js"></script>
<script charset="utf-8" src="/static/plugins/kindeditor/kindeditor-all-min.js"></script>
<script charset="utf-8" src="/static/plugins/kindeditor/lang/zh-CN.js"></script>

<script>
    KindEditor.ready(function (K) {
        window.editor = K.create('#content', {
            uploadJson: "/fault-report/upload-img/",
            extraFileUploadParams: {  // 上传文件时额外传递的参数
                csrfmiddlewaretoken: $("[name='csrfmiddlewaretoken']").val(),
            }
        });
    });
</script>
</body>
</html>

templates/index.html
{% extends "base.html" %}
{% block page-css %}
    <link rel="stylesheet" href="/static/plugins/bootstrap-3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/index.css">

{% endblock %}

{% block page-left %}
     <div class="panel panel-info">
                <div class="panel-heading">业务线分类</div>
                <div class="panel-body">
                    {% for lob in lob_list %}
{#                        <p><a href="">{{ lob.title }}({{ lob.faultreport_set.count }})</a></p>#}
                        <p><a href="/fault-report/lob/{{ lob.title }}/">{{ lob.title }}({{ lob.num }})</a></p>
                    {% endfor %}
                </div>
            </div>
            <div class="panel panel-success">
                <div class="panel-heading">标签分类</div>
                <div class="panel-body">
                    {% for tag in tag_list %}
                        <p><a href="/fault-report/tag/{{ tag.title }}/">{{ tag.title }}({{ tag.num }})</a></p>
                    {% endfor %}

                </div>
            </div>
            <div class="panel panel-warning">
                <div class="panel-heading">日期归档</div>
                <div class="panel-body">
                    {% for archive in archive_list %}
                        <p><a href="/fault-report/archive/{{ archive.ym }}/">{{ archive.ym }}({{ archive.num }})</a></p>
                    {% endfor %}
                </div>
            </div>

{% endblock %}

{% block page-right %}
     <div class="report-list">
                {% for report in report_list %}
                    <div class="report">
                        <div class="report-title">
{#                            title#}
                            <h3><a href="/fault-report/report/{{ report.id }}">{{ report.title }}</a></h3>
                        </div>
                        <div class="report-desc">
{#                            //简介#}
                            <p>{{ report.desc }}</p>
                        </div>
                        <div class="report-info">
                            <span>{{ report.user.username }}发布于</span>
                            <span>{{ report.create_time }}</span>
                            <span class="glyphicon glyphicon-comment" aria-hidden="true">评论({{ report.comment_count }})</span>
                            <span class="glyphicon glyphicon-thumbs-up" aria-hidden="true">支持({{ report.up_count }})</span>
                            <hr style="height: 1px;background-color: black; ">
                        </div>
                    </div>
                {% endfor %}
    {{ page_html|safe }}
     </div>
{% endblock %}

templates/info.html
{% extends 'base.html' %}
{% block page-left %}
    <div class="panel panel-info">
        <div class="panel-heading">
            <h3 class="panel-title">内容管理</h3>
        </div>
        <div class="panel-body">
            <a class="btn btn-default btn-block" href="/fault-report/add-report/">发布</a>
            <hr>
            <p><a href="">我的评论</a></p>
        </div>
    </div>
    <div class="panel panel-info">
        <div class="panel-heading">
            <h3 class="panel-title">资料管理</h3>
        </div>
        <div class="panel-body">
            <p><a href="/change_password/">修改密码</a></p>
            <p><a href="/edit_info/">修改信息</a></p>
        </div>
    </div>
{% endblock %}

{% block page-right %}
    <table class="table table-striped">
        <thead>
        <tr>
            <th>序号</th>
            <th>标题</th>
            <th>评论数</th>
            <th>支持数</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        {% for report in report_list %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td><a href="/fault-report/report/{{ report.id }}">{{ report.title }}</a></td>
                <td>{{ report.comment_count }}</td>
                <td>{{ report.up_count }}</td>
                <td>
                    <a class="btn btn-danger btn-sm" href="/fault-report/del-report/{{ report.id }}/">删除</a>
                    <a href="/fault-report/edit-report/{{ report.id }}/" class="btn btn-warning btn-sm">编辑</a>
                </td>
            </tr>
        {% endfor %}
{% endblock %}

templates/register.html
{#<!--注释#}
{# form_obj就是<label for="id_username">用户名:</label></th><td><input type="text" name="username" minlength="2"#}
{#class="form-control" required id="id_username" />#}
{#{{ field.id_for_label }} 就是id#}
{#{{ field.label }}就是字段名#}
{#{{ field }}就是input标签#}
{##}
{##}
{##}
{% extends "monther/monther.html" %}

{% block page-css %}
    <link rel="stylesheet" href="/static/plugins/bootstrap-3.3.7/css/bootstrap.min.css">

{% endblock %}

{% block page-main %}
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <form class="register-form" method="post">
                    {% csrf_token %}
                    {% for field in form_obj %}
                        <div class="form-group">
                            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                            {{ field }}
                            <span class="help-block"></span>
                        </div>
                    {% endfor %}
                    <div class="form-group">
                        <label for="id_avatar">头像<img src="/static/images/default.png" id="avatar-img" style="width: 60px">
                        </label>
                        <input type="file" id="id_avatar" accept="image/*" class="form-control" style="display: none">
                    </div>
                    <div style="text-align: center">
                        <button style="width: 100px" type="button" class="btn btn-success" id="submit-btn">提交</button>

                    </div>

                </form>
            </div>
        </div>

    </div>
{% endblock %}

{% block page-js %}

    <script src="/static/js/register.js"></script>
{% endblock %}

templates/report_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>故障总结详情页</title>
    <link rel="stylesheet" href="/static/plugins/bootstrap-3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/report_detail.css">
</head>
<body>
{% include "nav.html" %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="report">
                <h1>{{ report.title }}</h1>
                <!-- 故障总结的内容 -->
                <p>{{ report.faultdetail.content|safe }}</p>
            </div>
        </div>
    </div>

    {% csrf_token %}

    <!-- 点赞 开始-->
    <div class="clearfix">
        <div id="div_digg">
            <div class="diggit s21">
                <span class="diggnum" id="digg_count">{{ report.up_count }}</span>
            </div>

            <div class="buryit s21" >
                <span class="burynum" id="bury_count">{{ report.down_count }}</span>
            </div>

            <div class="clearfix"></div>
            <div class="diggword" id="digg_tips">

            </div>
        </div>
    </div>
    <!-- 点赞 结束-->
    <hr>
    <!-- 评论展示区 开始-->
    <div class="comment-list">
        <p>评论楼：</p>
        <div class="list-group">
            {% for comment in report.comment_set.all %}
             <div class="list-group-item">
                <h4 class="list-group-item-heading" s21="{{ comment.id }}">
                    <span>{{ forloop.counter }}楼</span>
                    <span>{{ comment.create_time }}</span>
                    <span>{{ comment.user.username }}</span>
                    <span class="replay pull-right">回复</span>
                </h4>
                 <!-- 判断当前的评论 有没有父评论，如果有父评论就展示 -->
                 {% if comment.parent_comment %}
                 <div class="list-group-item-text well">
                 @{{ comment.parent_comment.user.username }}
                 <p>{{ comment.parent_comment.content }}</p>
                 </div>
                 {% endif %}
                <p class="list-group-item-text">
                    {{ comment.content }}
                </p>
            </div>

            {% endfor %}
<!--
            <div class="list-group-item">
                <h4 class="list-group-item-heading">
                    <span>1楼</span>
                    <span>2018-09-09</span>
                    <span>alex</span>
                </h4>
                <p class="list-group-item-text">
                    说的真是太好了！支持一波！
                </p>
            </div>
        -->
        </div>
    </div>
    <!-- 评论展示区 结束-->

    <hr>

    <!-- 发表评论区 开始-->
    <div class="comment-box">
        <div class="panel panel-primary">
      <div class="panel-heading">发表评论</div>
      <div class="panel-body">
        <div>用户名：{{ request.user.username }}</div>
          <div>
              <textarea id="content"  cols="60" rows="10"></textarea>
          </div>

          <button class="btn btn-success" id="submit-comment">发表评论</button>
      </div>
    </div>

    </div>
    <!-- 发表评论区 结束-->
</div>
<script src="/static/plugins/jquery-3.3.1.min.js"></script>
<script>
    // 点赞操作
    $(".s21").click(function () {
        // 取到点赞操作需要的三个数据
        // 1. 谁 2. 哪篇文章 3. 支持or反对
        var userId = {{  request.user.id }};
        var reportId = {{ report.id }};
        var isUp = $(this).hasClass("diggit");

        // 往后端发送请求，创建点赞记录
        $.ajax({
            url: "/fault-report/updown/",  // 《up&down》 韩国女团 非常sexy
            type: 'post',
            data: {
                "user_id": userId,
                "report_id": reportId,
                "is_up": isUp,
                "csrfmiddlewaretoken": $("[name='csrfmiddlewaretoken']").val() // 一定不要忘了
            },
            success: function (res) {
                console.log(res);
                if (res.code === 1){
                    // 有错误就展示错误提示信息
                    $("#digg_tips").text(res.msg);
                }else {
                    // 点赞记录已经创建，在页面上展示效果
                    // 1. +1操作
                    if (isUp) {
                        // 点赞数+1
                        var $upEle = $("#digg_count");
                        var oldNum = $upEle.text();
                        $upEle.text(parseInt(oldNum) + 1);
                    }else {
                        // 反对数+1
                        var $downEle = $("#bury_count");
                        var oldNum = $downEle.text();
                        $downEle.text(+oldNum + 1);
                    }
                    // 2. 展示成功的提示信息
                    $("#digg_tips").text(res.msg);
                }
            }
        })
    });

    var parentId;

    // 发表评论
    $("#submit-comment").click(function () {
        // 1. 文章id  2. 谁 3. 评论的内容
        var reportId = {{ report.id }};
        var oldContent = $("#content").val(); // 要把@提示内容去掉
        var content = oldContent.slice(oldContent.indexOf("\n")+1,);
        console.log(parentId);
        $.ajax({
            url: "/fault-report/comment/",
            type: "post",
            data: {
                "report_id": reportId,
                "content": content,
                "parent_id": parentId,
                "csrfmiddlewaretoken": $("[name='csrfmiddlewaretoken']").val() // 一定不要忘了
            },
            success:function (res) {
                console.log(res);
                if (res.code === 0){
                    // 手动的绘制一个评论楼，用的模板字符串
                    var s = `
                                <div class="list-group-item">
                <h4 class="list-group-item-heading" s21="${res.data.id}">
                    <span>${res.data.n}楼</span>
                    <span>${res.data.create_time}</span>
                    <span>${res.data.user}</span>
                    <span class="replay pull-right">回复</span>
                </h4>
                <p class="list-group-item-text">
                    ${res.data.content}
                </p>`;
                    // 将创建好的评论楼 追加到评论列表中
                    // 也就是将s字符串追加到 comment-list 下面的 div中
                    $(".comment-list>div").append(s);
                    // 清空评论输入框
                    $("#content").val("");
                    // 清空全局变量
                    parentId = undefined;
                }
            }
        })
    });


    // 给回复 按钮绑定事件
    //$(".replay").click(function () {

    $(".comment-list").on("click", ".replay",  function () {
        // 1. 光标聚焦到评论的输入框里面
        // 2. 获取回复的是谁
        var replayName = $(this).prev().text();
        console.log(replayName);
        console.log("@" + replayName +"\n");
        $("#content").val("@" + replayName +"\n").focus();  // 获取焦点
        // 只要点击了回复按钮，就把全局变量保存为回复的评论的id值
        parentId = $(this).parent().attr("s21");
    })

</script>
</body>
</html>